/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package serverresttest;

import com.github.javafaker.Faker;
import io.restassured.RestAssured;
import org.apache.http.HttpStatus;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayNameGeneration;
import org.junit.jupiter.api.DisplayNameGenerator;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.is;

@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
class ServeRestTest {

    @BeforeAll
    static void beforeAll() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.baseURI = "https://serverest.dev";
    }

    @Test
    void create_account_successfully() {
        UserRequest userRequest = new UserRequest(
                Faker.instance().name().fullName(),
                Faker.instance().internet().emailAddress(),
                Faker.instance().internet().password(),
                "true"
        );

        given().
                contentType("application/json").
                accept("application/json").
                body(userRequest).
                when().
                post("/usuarios").
                then().
                assertThat().
                body("message", is("Cadastro realizado com sucesso")).
                statusCode(HttpStatus.SC_CREATED);
    }

    @Test
    void login_successfully() {
        UserRequest userRequest = new UserRequest(
                Faker.instance().name().fullName(),
                Faker.instance().internet().emailAddress(),
                Faker.instance().internet().password(),
                "true"
        );

        LoginRequest loginRequest = new LoginRequest(userRequest);

        given().
                contentType("application/json").
                accept("application/json").
                body(userRequest).
                when().
                post("/usuarios");

        given().
                contentType("application/json").
                accept("application/json").
                body(loginRequest).
                when().
                post("/login").
                then().
                assertThat().
                body("message", is("Login realizado com sucesso")).
                statusCode(HttpStatus.SC_OK);

    }
}
